<?php
/** @var \HE\TwoFactorAuth\Block\Adminhtml\System\Config\Fieldset\Hint $block */
/** @var \HE\TwoFactorAuth\Helper\Data $helper */
$helper = $this->helper('HE\TwoFactorAuth\Helper\Data');

$_moduleVersion = $helper->getVersion();
$_heLink = $helper->getHeLink();
$_nexcessLink= $helper->getNexcessLink();
$_docsLink = $helper->getDocsLink();
$_submitBugLink = $helper->getSubmitBugLink();
//$_multiAuthLink = $helper->getMultiAuthLink();
$_mageSupportLink = $helper->getMageSupportLink();
$_contactLink = $helper->getContactLink();
?>

<div class="sentry-intro">
	<div class="line">
		<?php echo __('Sentry Two-Factor Authentication for Magento v%1', $_moduleVersion); ?>
	</div>
	<div class="line">
		<?php echo __('Developed as a Partnership between <a href="%1" target="_blank">Human Element</a> and <a href="%2" target="_blank">Nexcess</a> Hosting', $_heLink, $_nexcessLink); ?>
	</div>
</div>
<div class="sentry-banner">
	<div class="sentry-ribbon">
		<?php echo __('<strong>Sentry</strong> Two-factor Authentication for Magento'); ?>
		<div class="btns">
			<a class="btn bug" href="<?php echo $_submitBugLink; ?>" target="_blank"><?php echo __('Submit a Bug'); ?></a>
			<a class="btn readme" href="<?php echo $_docsLink; ?>" target="_blank"><?php echo __('Read Me'); ?></a>
		</div>
	</div>
	<p>Multifactor authentication provides an additional check when logging into your Magento administration system. 
		Once configured, an additional challenge screen is added to the admin login process. This screen will interact 
		with an additional method of contact, usually a cellphone or email, that will prove that the user attempting login is the real user.</p>
	<p>NOTE - when using multifactor authentication it is highly advised that each admin user have their own account.</p>
	<p>To find out more about Human Element and <a href="<?php echo $_mageSupportLink ?>" target="_blank">Magento Support Services</a>, please visit our website at 
		<a href="<?php echo $_heLink ?>" target="_blank"><?php echo $block->simplifyLinkLabel($_heLink); ?></a>
		or fill in our <a href="<?php echo $_contactLink; ?>" target="_blank">contact form</a>. 
		To find out more about Nexcess Hosting, visit their website at 
		<a href="<?php echo $_nexcessLink; ?>" target="_blank"><?php echo $block->simplifyLinkLabel($_nexcessLink); ?></a>. </p>
</div>
